In [1]:
import pandas as pd
import os
import pyreadstat
import numpy as np

## Etapa regular

In [42]:
BD= pd.read_excel("C:\\Users\\User\\OneDrive - Universidad Torcuato Di Tella\\2. PC TUF reforzada\\MINEDU 2026\\Repositorios\\MINEDU-2026-05-INF_NACIONAL_EDDIR_IE_REG_EXCEP_2024_2025\\Inputs\\Consolidado_EDDirIE2024_22-12-2025_act.xlsx",
                  sheet_name="Consolidado_EDDirIE2024_22-12-2", dtype={"Documento":str, "Codigo_modular":str, "CÓDIGODEPLAZA":str}
                  )

In [43]:
BD.shape

(5785, 165)

In [45]:
BD["DIF_sex"] = np.where(BD["sex"] == 1, "Masculino", "Femenino")
BD["DIF_rango_edad"] = np.select(
    [((BD["edad"]>=30) & (BD["edad"]<=39)),
     ((BD["edad"]>=40) & (BD["edad"]<=49)),
     ((BD["edad"]>=50) & (BD["edad"]<=59)),
     ((BD["edad"]>=60))
     ],
    ["30-39", "40-49", "50-59", "60 a más"],
    default="Revisar"
)

BD["DIF_Perfil_evaluado"] = BD["DesTipDirectivo"].str.cat(BD["DesPerfil"], sep=" ")
BD["DIF_Mod_Perfil_evaluado"] = (
    BD["ModalidadEducativa"]
    .str.cat(BD["DesTipDirectivo"], sep=" - ")
    .str.cat(BD["DesPerfil"], sep=" - "))
BD["DIF_D1S2"] = np.where(BD["DIF_Perfil_evaluado"]=="Director Con función docente", np.nan, BD["D1S2"])
BD["DIF_D3S10"] = np.where(BD["DIF_Perfil_evaluado"]=="Subdirector Ninguno", np.nan, BD["D3S10"])
BD["DIF_D3S11"] = np.where(BD["DIF_Perfil_evaluado"]=="Subdirector Ninguno", np.nan, BD["D3S11"])

In [46]:
columnas_drop = [
    "ID", "tipo_doc", "ff", "ApePaternoEvaluado", "ApeMaternoEvaluado", "NombreEvaluado", "sex",
    "fecha_nac", "IDLista", "IDEvaluacion", "CodLocal", "NombreIE", "area", "Evaluado_anterior",
    "ESTADODEEVALUACIÓN_anterior", "Evaluado_actualizado", "fecha_pub_hab", "edad", "edquin", "grupedad",
    "HABILITADO", "CÓDIGOMODULAR", "MOTIVOOBSERVACIÓN_anterior", "OBSERVACIÓN"
]

BD.drop(columns=columnas_drop, inplace=True)

In [47]:
BD

,Documento,escala_final,Region,DreUgel,SeRealizoEvaluacion_actualizado,MotivoNoEvaluacion_actualizado,DesTipDirectivo,DesPerfil,ModalidadEducativa,DesNivelEducativo,...,D3S11C7,ESTADODEEVALUACIÓN_actualizado,CÓDIGODEPLAZA,DIF_sex,DIF_rango_edad,DIF_Perfil_evaluado,DIF_Mod_Perfil_evaluado,DIF_D1S2,DIF_D3S10,DIF_D3S11
0,00001873,3,UCAYALI,UGEL CORONEL PORTILLO,No,Retiro de la CPM por renuncia formal al cargo ...,Director,Sin función docente,EBR,Ed. Básica Regular Primaria,...,NaN,NO EVALUADO,1121113131I6,Masculino,60 a más,Director Sin función docente,EBR - Director - Sin función docente,NaN,NaN,NaN
1,00011467,4,UCAYALI,UGEL CORONEL PORTILLO,Sí,-,Director,Sin función docente,EBR,Ed. Básica Regular Primaria,...,No cumple,PENDIENTE,1132614311I4,Masculino,50-59,Director Sin función docente,EBR - Director - Sin función docente,2.0,2.0,2.0
2,00012733,4,UCAYALI,UGEL CORONEL PORTILLO,Sí,-,Director,Con función docente,EBR,Ed. Básica Regular Secundaria,...,Cumple,APROBADO,1140114111I3,Femenino,60 a más,Director Con función docente,EBR - Director - Con función docente,NaN,2.0,4.0
3,00015479,5,UCAYALI,UGEL CORONEL PORTILLO,No,Retiro de la CPM por renuncia formal al cargo ...,Director,Sin función docente,EBR,Ed. Básica Regular Primaria,...,NaN,NO EVALUADO,1122313131I8,Femenino,60 a más,Director Sin función docente,EBR - Director - Sin función docente,NaN,NaN,NaN
4,00015657,4,UCAYALI,UGEL CORONEL PORTILLO,No,Retiro de la CPM por límite de edad,Director,Sin función docente,EBA,Ed. Básica Alternativa,...,NaN,NO EVALUADO,1161115111I5,Masculino,60 a más,Director Sin función docente,EBA - Director - Sin función docente,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5780,80351513,6,HUÁNUCO,UGEL HUÁNUCO,Sí,-,Director,Con función docente,EBR,Ed. Básica Regular Primaria,...,Cumple,APROBADO,520861219918,Masculino,40-49,Director Con función docente,EBR - Director - Con función docente,NaN,2.0,4.0
5781,80373161,4,PUNO,UGEL CARABAYA,Sí,-,Director,Sin función docente,EBR,Ed. Básica Regular Primaria,...,Cumple,APROBADO,1134113010Q6,Masculino,40-49,Director Sin función docente,EBR - Director - Sin función docente,1.0,4.0,4.0
5782,80416941,5,PUNO,UGEL PUNO,Sí,-,Director,Con función docente,EBR,Ed. Básica Regular Secundaria,...,Cumple,PENDIENTE,1163114811E9,Masculino,40-49,Director Con función docente,EBR - Director - Con función docente,NaN,2.0,4.0
5783,80537531,5,AMAZONAS,UGEL UTCUBAMBA,Sí,-,Director,Con función docente,EBR,Ed. Básica Regular Primaria,...,Cumple,APROBADO,1107313414N3,Masculino,40-49,Director Con función docente,EBR - Director - Con función docente,NaN,4.0,4.0
5784,80550457,6,HUÁNUCO,UGEL HUÁNUCO,No,Renuncia formal al cargo en el que ha sido des...,Subdirector,Ninguno,EBR,Ed. Básica Regular Primaria,...,NaN,NO EVALUADO,525851214918,Masculino,40-49,Subdirector Ninguno,EBR - Subdirector - Ninguno,NaN,NaN,NaN

In [24]:
tabla = pd.crosstab(
    BD["SeRealizoEvaluacion_actualizado"],
    BD["ESTADODEEVALUACIÓN_actualizado"],
    dropna=True,
    margins=True
)

print(tabla.to_markdown())

| SeRealizoEvaluacion_actualizado   |   APROBADO |   DESAPROBADO |   NO EVALUADO |   PENDIENTE |   All |
|:----------------------------------|-----------:|--------------:|--------------:|------------:|------:|
| No                                |          0 |             0 |           170 |           0 |   170 |
| Sí                                |       3183 |           201 |             0 |        2231 |  5615 |
| All                               |       3183 |           201 |           170 |        2231 |  5785 |

In [26]:
tabla = pd.crosstab(
    BD["MotivoNoEvaluacion_actualizado"],
    BD["SeRealizoEvaluacion_actualizado"],
    dropna=True,
    margins=True
)

print(tabla.to_markdown())

| MotivoNoEvaluacion_actualizado                           |   No |   Sí |   All |
|:---------------------------------------------------------|-----:|-----:|------:|
| -                                                        |    0 | 5615 |  5615 |
| Renuncia formal al cargo en el que ha sido designado     |   64 |    0 |    64 |
| Retiro de la CPM por destitución con resolución firme    |    2 |    0 |     2 |
| Retiro de la CPM por fallecimiento                       |    7 |    0 |     7 |
| Retiro de la CPM por límite de edad                      |   34 |    0 |    34 |
| Retiro de la CPM por renuncia formal al cargo de docente |   63 |    0 |    63 |
| All                                                      |  170 | 5615 |  5785 |

In [50]:
tabla = pd.crosstab(
    BD["DIF_Mod_Perfil_evaluado"],
    BD["SeRealizoEvaluacion_actualizado"],
    dropna=True,
    margins=True
)

print(tabla.to_markdown())

| DIF_Mod_Perfil_evaluado              |   No |   Sí |   All |
|:-------------------------------------|-----:|-----:|------:|
| EBA - Director - Con función docente |    0 |   15 |    15 |
| EBA - Director - Sin función docente |    1 |   35 |    36 |
| EBA - Subdirector - Ninguno          |    6 |  127 |   133 |
| EBE - Director - Con función docente |    1 |    4 |     5 |
| EBE - Director - Sin función docente |    0 |   42 |    42 |
| EBE - Subdirector - Ninguno          |    0 |    1 |     1 |
| EBR - Director - Con función docente |   54 | 1762 |  1816 |
| EBR - Director - Sin función docente |   78 | 2638 |  2716 |
| EBR - Subdirector - Ninguno          |   30 |  991 |  1021 |
| All                                  |  170 | 5615 |  5785 |

In [63]:
filtro = BD["DIF_Perfil_evaluado"] == "Director Con función docente"

resumen = pd.concat(
    [
        BD.loc[filtro, "D1S2"].value_counts(dropna=False).rename("D1S2"),
        BD.loc[filtro, "DIF_D1S2"].value_counts(dropna=False).rename("DIF_D1S2")
    ],
    axis=1
)

resumen.reset_index(inplace=True)
print(resumen.to_markdown())

|    |   index |   D1S2 |   DIF_D1S2 |
|---:|--------:|-------:|-----------:|
|  0 |       0 |   1781 |        nan |
|  1 |     nan |     55 |       1836 |

In [64]:
filtro = BD["DIF_Perfil_evaluado"] == "Subdirector Ninguno"

resumen = pd.concat(
    [
        BD.loc[filtro, "D3S10"].value_counts(dropna=False).rename("D3S10"),
        BD.loc[filtro, "DIF_D3S10"].value_counts(dropna=False).rename("DIF_D3S10")
    ],
    axis=1
)

resumen.reset_index(inplace=True)
print(resumen.to_markdown())

|    |   index |   D3S10 |   DIF_D3S10 |
|---:|--------:|--------:|------------:|
|  0 |       0 |    1119 |         nan |
|  1 |     nan |      36 |        1155 |

In [65]:
filtro = BD["DIF_Perfil_evaluado"] == "Subdirector Ninguno"

resumen = pd.concat(
    [
        BD.loc[filtro, "D3S11"].value_counts(dropna=False).rename("D3S11"),
        BD.loc[filtro, "DIF_D3S11"].value_counts(dropna=False).rename("DIF_D3S11")
    ],
    axis=1
)

resumen.reset_index(inplace=True)
print(resumen.to_markdown())

|    |   index |   D3S11 |   DIF_D3S11 |
|---:|--------:|--------:|------------:|
|  0 |       0 |    1119 |         nan |
|  1 |     nan |      36 |        1155 |

In [66]:
BD.to_excel("C:\\Users\\User\\OneDrive - Universidad Torcuato Di Tella\\2. PC TUF reforzada\\MINEDU 2026\\Repositorios\\MINEDU-2026-05-INF_NACIONAL_EDDIR_IE_REG_EXCEP_2024_2025\\Outputs\\BD_DIF_EddirIE_2024_Reg_240526.xlsx", index=False )

In [67]:
BD

,Documento,escala_final,Region,DreUgel,SeRealizoEvaluacion_actualizado,MotivoNoEvaluacion_actualizado,DesTipDirectivo,DesPerfil,ModalidadEducativa,DesNivelEducativo,...,D3S11C7,ESTADODEEVALUACIÓN_actualizado,CÓDIGODEPLAZA,DIF_sex,DIF_rango_edad,DIF_Perfil_evaluado,DIF_Mod_Perfil_evaluado,DIF_D1S2,DIF_D3S10,DIF_D3S11
0,00001873,3,UCAYALI,UGEL CORONEL PORTILLO,No,Retiro de la CPM por renuncia formal al cargo ...,Director,Sin función docente,EBR,Ed. Básica Regular Primaria,...,NaN,NO EVALUADO,1121113131I6,Masculino,60 a más,Director Sin función docente,EBR - Director - Sin función docente,NaN,NaN,NaN
1,00011467,4,UCAYALI,UGEL CORONEL PORTILLO,Sí,-,Director,Sin función docente,EBR,Ed. Básica Regular Primaria,...,No cumple,PENDIENTE,1132614311I4,Masculino,50-59,Director Sin función docente,EBR - Director - Sin función docente,2.0,2.0,2.0
2,00012733,4,UCAYALI,UGEL CORONEL PORTILLO,Sí,-,Director,Con función docente,EBR,Ed. Básica Regular Secundaria,...,Cumple,APROBADO,1140114111I3,Femenino,60 a más,Director Con función docente,EBR - Director - Con función docente,NaN,2.0,4.0
3,00015479,5,UCAYALI,UGEL CORONEL PORTILLO,No,Retiro de la CPM por renuncia formal al cargo ...,Director,Sin función docente,EBR,Ed. Básica Regular Primaria,...,NaN,NO EVALUADO,1122313131I8,Femenino,60 a más,Director Sin función docente,EBR - Director - Sin función docente,NaN,NaN,NaN
4,00015657,4,UCAYALI,UGEL CORONEL PORTILLO,No,Retiro de la CPM por límite de edad,Director,Sin función docente,EBA,Ed. Básica Alternativa,...,NaN,NO EVALUADO,1161115111I5,Masculino,60 a más,Director Sin función docente,EBA - Director - Sin función docente,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5780,80351513,6,HUÁNUCO,UGEL HUÁNUCO,Sí,-,Director,Con función docente,EBR,Ed. Básica Regular Primaria,...,Cumple,APROBADO,520861219918,Masculino,40-49,Director Con función docente,EBR - Director - Con función docente,NaN,2.0,4.0
5781,80373161,4,PUNO,UGEL CARABAYA,Sí,-,Director,Sin función docente,EBR,Ed. Básica Regular Primaria,...,Cumple,APROBADO,1134113010Q6,Masculino,40-49,Director Sin función docente,EBR - Director - Sin función docente,1.0,4.0,4.0
5782,80416941,5,PUNO,UGEL PUNO,Sí,-,Director,Con función docente,EBR,Ed. Básica Regular Secundaria,...,Cumple,PENDIENTE,1163114811E9,Masculino,40-49,Director Con función docente,EBR - Director - Con función docente,NaN,2.0,4.0
5783,80537531,5,AMAZONAS,UGEL UTCUBAMBA,Sí,-,Director,Con función docente,EBR,Ed. Básica Regular Primaria,...,Cumple,APROBADO,1107313414N3,Masculino,40-49,Director Con función docente,EBR - Director - Con función docente,NaN,4.0,4.0
5784,80550457,6,HUÁNUCO,UGEL HUÁNUCO,No,Renuncia formal al cargo en el que ha sido des...,Subdirector,Ninguno,EBR,Ed. Básica Regular Primaria,...,NaN,NO EVALUADO,525851214918,Masculino,40-49,Subdirector Ninguno,EBR - Subdirector - Ninguno,NaN,NaN,NaN

## Etapa excepcional

In [10]:
BD2, metaexcep = pyreadstat.read_sav("/Users/cristianmolina/Desktop/BD_EDDIR_Reg_Excep/Inputs/Consolidado_EDDIR-IE_Excepcional_13.02.2026.sav")

In [70]:
metaexcep.value_labels

{'labels0': {1.0: 'DNI', 5.0: 'CE', 8.0: 'PASAPORTE'},
 'labels1': {1.0: 'Masculino', 2.0: 'Femenino'},
 'labels2': {2.0: 'De 25 a 29 años',
  3.0: 'De 30 a 34 años',
  4.0: 'De 35 a 39 años',
  5.0: 'De 40 a 44 años',
  6.0: 'De 45 a 49 años',
  7.0: 'De 50 a 54 años',
  8.0: 'De 55 a 59 años',
  9.0: 'De 60 a 65 años'},
 'labels3': {1.0: 'De 25 a 29 años',
  2.0: 'De 30 a 39 años',
  3.0: 'De 40 a 49 años',
  4.0: 'De 50 a 59 años',
  5.0: 'De 60 a más años'},
 'labels4': {0.0: 'Not Selected', 1.0: 'Selected'}}

In [18]:
BD2["EstadoEvaluacion"].value_counts(dropna=False)

EstadoEvaluacion
DESAPROBADO    1080
APROBADO        769
NO EVALUADO     167
EN PROCESO       45
Name: count, dtype: int64

In [17]:
Resultados = pd.read_excel("/Users/cristianmolina/Desktop/BD_EDDIR_Reg_Excep/Inputs/Entrega Informacion 13022026 1415.xlsx",
                           sheet_name="Criterios", dtype = {"DocumentoIdentidad":str}
                           )

In [59]:
Resultados_pivo2 = Resultados.groupby(["DocumentoIdentidad", "CodigoCriterio"])["DesCalificacionCriterio"]\
    .apply(lambda x: ", ".join(x.dropna().astype(str).unique())).reset_index()
    
Resultados_pivo3 = Resultados_pivo2.pivot(index = "DocumentoIdentidad",
                             columns = "CodigoCriterio",
                             values = "DesCalificacionCriterio"
                             )

Resultados_pivo3

CodigoCriterio,D1S1C1,D1S1C1_EBA,D1S1C2,D1S1C2_EBA,D1S1C3,D1S1C3_EBA,D1S1C4,D1S1C5,D1S1C5_EBA,D1S1C6,...,D3S8C5,D3S8C6,D3S8C7,D3S8C8,D3S9C1,D3S9C2,D3S9C3,D3S9C4,D3S9C5,D3S9C6
DocumentoIdentidad,,,,,,,,,,,,,,,,,,,,,
00011467,Cumple,NaN,Cumple,NaN,Cumple,NaN,No cumple,Cumple,NaN,Cumple,...,Cumple,Cumple,No cumple,Cumple,Cumple,Cumple,No cumple,No cumple,No cumple,No cumple
00021195,Cumple,NaN,Cumple,NaN,Cumple,NaN,No cumple,Cumple,NaN,Cumple,...,No cumple,No cumple,Cumple,No cumple,No cumple,No cumple,No cumple,No cumple,No cumple,No cumple
00022644,Cumple,NaN,No cumple,NaN,No cumple,NaN,No cumple,Cumple,NaN,No cumple,...,No cumple,No cumple,Cumple,No cumple,No cumple,No cumple,No cumple,No cumple,No cumple,No cumple
00054857,Cumple,NaN,Cumple,NaN,Cumple,NaN,No cumple,Cumple,NaN,Cumple,...,No cumple,No cumple,Cumple,No cumple,No cumple,Cumple,No cumple,No cumple,No cumple,Cumple
00088692,NaN,Cumple,NaN,Cumple,NaN,Cumple,Cumple,NaN,Cumple,NaN,...,Cumple,Cumple,Cumple,Cumple,Cumple,No cumple,Cumple,Cumple,Cumple,Cumple
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41009855,Cumple,NaN,Cumple,NaN,Cumple,NaN,Cumple,Cumple,NaN,Cumple,...,Cumple,Cumple,Cumple,Cumple,Cumple,Cumple,Cumple,Cumple,Cumple,Cumple
41302122,Cumple,NaN,Cumple,NaN,Cumple,NaN,No cumple,Cumple,NaN,Cumple,...,No cumple,Cumple,Cumple,No cumple,No cumple,No cumple,No cumple,Cumple,Cumple,Cumple
41376175,Cumple,NaN,Cumple,NaN,No cumple,NaN,Cumple,Cumple,NaN,No cumple,...,Cumple,Cumple,Cumple,Cumple,Cumple,No cumple,Cumple,Cumple,Cumple,Cumple
80019734,No cumple,NaN,Cumple,NaN,Cumple,NaN,Cumple,Cumple,NaN,Cumple,...,Cumple,No cumple,Cumple,Cumple,Cumple,Cumple,Cumple,Cumple,No cumple,No cumple
80066895,Cumple,NaN,Cumple,NaN,Cumple,NaN,Cumple,Cumple,NaN,Cumple,...,Cumple,Cumple,Cumple,Cumple,No cumple,No cumple,Cumple,Cumple,Cumple,Cumple

In [78]:
BD2_f = pd.merge(BD2, Resultados_pivo3,
         left_on="Documento",
         right_on="DocumentoIdentidad",
         how="left"
         )

In [79]:
BD2_f["sex"] = np.where(BD2_f["sex"] == 1, "Masculino", "Femenino")
BD2_f["DIF_rango_edad"] = np.select(
    [((BD2_f["edad"]>=30) & (BD2_f["edad"]<=39)),
     ((BD2_f["edad"]>=40) & (BD2_f["edad"]<=49)),
     ((BD2_f["edad"]>=50) & (BD2_f["edad"]<=59)),
     ((BD2_f["edad"]>=60))
     ],
    ["30-39", "40-49", "50-59", "60 a más"],
    default="Revisar"
)
BD2_f["DIF_Perfil_evaluado"] = BD2_f["TipoDirectivo"].str.cat(BD2_f["PerfilDocente"], sep=" ")

BD2_f["DIF_D1S2"] = np.where(BD2_f["DIF_Perfil_evaluado"]=="Director Con función docente", np.nan, BD2_f["SubDimension2"])
BD2_f["DIF_D3S10"] = np.where(BD2_f["DIF_Perfil_evaluado"]=="Subdirector Ninguno", np.nan, BD2_f["SubDimension10"])
BD2_f["DIF_D3S11"] = np.where(BD2_f["DIF_Perfil_evaluado"]=="Subdirector Ninguno", np.nan, BD2_f["SubDimension11"])

In [86]:
BD2_f.to_excel("/Users/cristianmolina/Desktop/BD_EDDIR_Reg_Excep/Outputs/BD_DIF_EddirIE_2024_Excp.xlsx",
               index=False,
               engine="openpyxl")

In [88]:
x,metax = pyreadstat.read_sav("/Users/cristianmolina/Downloads/Habilitados_EDDirIE_A6_12022025.sav")
x

,N°,REGIÓN,DREUGEL,DNI,APELLIDOPATERNO,APELLIDOMATERNO,NOMBRES,CARGO,CÓDIGODEPLAZA,MODALIDAD,...,CARACTERÍSTICADELAI.E,OBSERVACIÓN,INFORMEN°01178,INFORMEN°01254,INFORMEN°01421,INFORMEN°01634,INFORMEN°02688,INFORMEN°02068_INFORMEN°2142,HABILITADO,ObservacionregistradaenlaPublicacióndel11072024
0,1.0,AMAZONAS,UGEL BAGUA,19188615,QUESQUEN,TESEN,JOSE JAIME,DIRECTOR I.E.,1154013314O3,EBR,...,POLIDOCENTE COMPLETO,,,,,,,,SÍ,
1,2.0,AMAZONAS,UGEL BAGUA,33561167,DIAZ,LOPEZ,LIZANDRO,DIRECTOR I.E.,1114013314O8,EBR,...,POLIDOCENTE COMPLETO,,,,,,,,SÍ,
2,3.0,AMAZONAS,UGEL BAGUA,33561555,GUEVARA,CARUAJULCA,JOSUE ARTURO,DIRECTOR I.E.,1137314514O0,EBR,...,POLIDOCENTE COMPLETO,,,,,,,,SÍ,
3,4.0,AMAZONAS,UGEL BAGUA,33561586,FERNANDEZ,FERNANDEZ,NERY ROSALITA,DIRECTOR I.E.,1185013414O3,EBR,...,POLIDOCENTE COMPLETO,,,,,,,,SÍ,
4,5.0,AMAZONAS,UGEL BAGUA,33562767,VARGAS,GUTIERREZ,JOSE ANTONIO,SUB-DIRECTOR I.E.,1175613514O5,EBR,...,POLIDOCENTE COMPLETO,,,,,,,,SÍ,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5859,62.0,UCAYALI,UGEL PADRE ABAD,22486042,AGUIRRE,LEANDRO,ANTONIO,DIRECTOR I.E.,1101114111K8,EBR,...,POLIDOCENTE COMPLETO,,,,,,,,SÍ,
5860,63.0,UCAYALI,UGEL PADRE ABAD,22494346,SALGADO,ARANDA,SAMUEL SANTIAGO,DIRECTOR I.E.,1161114111K5,EBR,...,POLIDOCENTE COMPLETO,,,,,,,,SÍ,
5861,64.0,UCAYALI,UGEL PADRE ABAD,22519425,CARNERO,SORIA,ROCIO DEL CARMEN,DIRECTOR I.E.,1113113111K2,EBR,...,POLIDOCENTE MULTIGRADO,Retirado de acuerdo al INFORME N° 02688-2024-M...,,,,,EXCLUIR,,NO,
5862,65.0,UCAYALI,UGEL PADRE ABAD,23018465,ACUÑA,TORRES,LIDIA,DIRECTOR I.E.,1181113111K4,EBR,...,POLIDOCENTE COMPLETO,Retirado de acuerdo al INFORME N° 01634-2024-M...,,,,EXCLUIR,,,NO,Incluido según MEMORANDUM N° 00523-2024-MINEDU...
5863,66.0,UCAYALI,UGEL PADRE ABAD,40078533,QUISPE,TICONA,WALTER,DIRECTOR I.E.,1151114111K2,EBR,...,POLIDOCENTE COMPLETO,,,,,,,,SÍ,

In [91]:
BD2_f

,ID,tipo_doc,Documento,APELLIDOPATERNO,APELLIDOMATERNO,NOMBRES,CARGO,Region,DreUgel,TipoDirectivo,...,D3S9C2,D3S9C3,D3S9C4,D3S9C5,D3S9C6,DIF_rango_edad,DIF_Perfil_evaluado,DIF_D1S2,DIF_D3S10,DIF_D3S11
0,193511.0,1.0,00011467,RIOS,CORDOVA,TONY,DIRECTOR I.E.,UCAYALI,UGEL CORONEL PORTILLO,Director,...,Cumple,No cumple,No cumple,No cumple,No cumple,50-59,Director Sin función docente,4,4,1
1,178037.0,1.0,00018014,PORTOCARRERO,GOMEZ,ITALO,DIRECTOR I.E.,LIMA METROPOLITANA,UGEL 02 RIMAC,Director,...,NaN,NaN,NaN,NaN,NaN,50-59,Director Sin función docente,-,-,-
2,91471.0,1.0,00021195,GARCIA,GOMEZ,VICTOR RAUL,DIRECTOR I.E.,UCAYALI,UGEL CORONEL PORTILLO,Director,...,No cumple,No cumple,No cumple,No cumple,No cumple,60 a más,Director Sin función docente,1,1,1
3,213283.0,1.0,00022644,SANCHEZ,PEÑA,SIVILA,DIRECTOR I.E.,UCAYALI,UGEL CORONEL PORTILLO,Director,...,No cumple,No cumple,No cumple,No cumple,No cumple,60 a más,Director Sin función docente,1,1,1
4,15529.0,1.0,00026295,AREVALO,ACOSTA,MARITZA LUCIA,SUB-DIRECTOR I.E.,UCAYALI,UGEL CORONEL PORTILLO,Subdirector,...,NaN,NaN,NaN,NaN,NaN,50-59,Subdirector Ninguno,-,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2056,245369.0,1.0,41376175,VELASQUEZ,PAPA,SANDRA ISABEL,SUB-DIRECTOR I.E.,LORETO,UGEL MAYNAS,Subdirector,...,No cumple,Cumple,Cumple,Cumple,Cumple,40-49,Subdirector Ninguno,1,NaN,NaN
2057,185540.0,1.0,80019734,QUISPE,YUCRA,RONALD,DIRECTOR I.E.,PUNO,UGEL PUNO,Director,...,Cumple,Cumple,Cumple,No cumple,No cumple,40-49,Director Sin función docente,1,2,2
2058,129910.0,1.0,80066895,MACHACA,CARI,EDWIN FREDY,DIRECTOR I.E.,PUNO,UGEL HUANCANÉ,Director,...,No cumple,Cumple,Cumple,Cumple,Cumple,40-49,Director Con función docente,NaN,3,1
2059,164927.0,1.0,80086887,PALOMINO,CASTRO,PEDRO,DIRECTOR I.E.,LIMA METROPOLITANA,UGEL 04 COMAS,Director,...,NaN,NaN,NaN,NaN,NaN,40-49,Director Sin función docente,-,-,-
2060,170936.0,1.0,80416941,PEÑALOZA,HUANCA,ALEXANDER RUSO,DIRECTOR I.E.,PUNO,UGEL PUNO,Director,...,NaN,NaN,NaN,NaN,NaN,40-49,Director Con función docente,NaN,-,-

## Revisión de infografia EDDIR - Regular

In [12]:
BD_R, meta_R = pyreadstat.read_sav("/Users/cristianmolina/Desktop/BD_EDDIR_Reg_Excep/Inputs/Consolidado_EDDirIE2024_22-12-2025.sav")

In [3]:
BD_R_DIF = pd.read_excel("/Users/cristianmolina/Desktop/BD_EDDIR_Reg_Excep/Outputs/BD_DIF_EddirIE_2024_Reg.xlsx",
                         dtype = {"Documento":str})

In [7]:
BD_R_DIF.groupby(["ModalidadEducativa", "DIF_Perfil_evaluado", "ESTADODEEVALUACIÓN_actualizado"])\
    .size()\
        .reset_index(name="n")\
            .assign(
                Indice = lambda x: x["ModalidadEducativa"] + " " + x["DIF_Perfil_evaluado"]
            )[["Indice", "ESTADODEEVALUACIÓN_actualizado", "n"]]\
                .pivot_table(index="Indice",
                             columns="ESTADODEEVALUACIÓN_actualizado",
                             values="n"
                             )

ESTADODEEVALUACIÓN_actualizado,APROBADO,DESAPROBADO,NO EVALUADO,PENDIENTE
Indice,,,,
EBA Director Con función docente,7.0,NaN,NaN,8.0
EBA Director Sin función docente,22.0,2.0,1.0,11.0
EBA Subdirector Ninguno,73.0,6.0,6.0,48.0
EBE Director Con función docente,2.0,NaN,1.0,2.0
EBE Director Sin función docente,23.0,2.0,NaN,17.0
EBE Subdirector Ninguno,1.0,NaN,NaN,NaN
EBR Director Con función docente,1068.0,58.0,54.0,636.0
EBR Director Sin función docente,1512.0,100.0,78.0,1026.0
EBR Subdirector Ninguno,475.0,33.0,30.0,483.0

In [17]:
BD_R_DIF.groupby(["ModalidadEducativa", "DIF_Perfil_evaluado", "ESTADODEEVALUACIÓN_actualizado"])\
    .size()\
        .reset_index(name="n").assign(
                Mod_Estado_Final = lambda x: x["ModalidadEducativa"] + " " + x["ESTADODEEVALUACIÓN_actualizado"]
            )[["DIF_Perfil_evaluado", "Mod_Estado_Final", "n"]]\
                .pivot_table(index="DIF_Perfil_evaluado",
                             columns="Mod_Estado_Final",
                             values="n"
                             )\
                                 .reset_index()\
                                     .to_excel("/Users/cristianmolina/Desktop/BD_EDDIR_Reg_Excep/Outputs/Tabla1_revINFG.xlsx",
                                               index=False)

In [31]:
BD_R_DIF.groupby(["Region", "ESTADODEEVALUACIÓN_actualizado"]).size()\
    .reset_index(name = "n")\
        .pivot_table(index = "Region",
                     columns="ESTADODEEVALUACIÓN_actualizado",
                     values="n")\
                         .assign(
                             EVALUADOS = lambda x: x["APROBADO"] + x["DESAPROBADO"] + x["PENDIENTE"]
                         ).to_excel("Tabla2_revINFG.xlsx")

In [32]:
BD_R_DIF

,ID,tipo_doc,Documento,ApePaternoEvaluado,ApeMaternoEvaluado,NombreEvaluado,sex,fecha_nac,escala_final,IDLista,...,HABILITADO,CÓDIGODEPLAZA,CÓDIGOMODULAR,filter_$,DIF_sex,DIF_rango_edad,DIF_Perfil_evaluado,DIF_D1S2,DIF_D3S10,DIF_D3S11
0,146653,1,00001873,MONCADA,GONZALES,LUIS ALBERTO,1,1961-04-02,3,5494,...,SÍ,1121113131I6,271205,1,Masculino,60 a más,Director Sin función docente,NaN,NaN,NaN
1,193511,1,00011467,RIOS,CORDOVA,TONY,1,1965-11-03,4,5495,...,SÍ,1132614311I4,1747971,0,Masculino,50-59,Director Sin función docente,2.0,2.0,2.0
2,213588,1,00012733,SANCHEZ,ROJAS,CLAUDIA LUZ,2,1962-05-14,4,5496,...,SÍ,1140114111I3,913939,0,Femenino,60 a más,Director Con función docente,NaN,2.0,4.0
3,213494,1,00015479,SANCHEZ,RIOS,CLOTILDE NATIVIDAD,2,1962-01-26,5,5497,...,SÍ,1122313131I8,271296,1,Femenino,60 a más,Director Sin función docente,NaN,NaN,NaN
4,143437,1,00015657,MERA,OROSCO,PASTOR,1,1959-06-13,4,5498,...,SÍ,1161115111I5,923383,1,Masculino,60 a más,Director Sin función docente,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5780,235543,1,80351513,URBANO,NIÑO,ROGELIO ELIAS,1,1976-12-19,6,2168,...,SÍ,520861219918,609503,0,Masculino,40-49,Director Con función docente,NaN,2.0,4.0
5781,66888,1,80373161,CUNO,PUMA,MARCOS ABEL,1,1978-10-08,4,4883,...,SÍ,1134113010Q6,811745,0,Masculino,40-49,Director Sin función docente,1.0,4.0,4.0
5782,170936,1,80416941,PEÑALOZA,HUANCA,ALEXANDER RUSO,1,1976-03-07,5,5643,...,SÍ,1163114811E9,744441,0,Masculino,40-49,Director Con función docente,NaN,2.0,4.0
5783,195576,1,80537531,RIVERA,PAREDES,JOHNNY,1,1979-04-14,5,5729,...,SÍ,1107313414N3,223578,0,Masculino,40-49,Director Con función docente,NaN,4.0,4.0
5784,12639,1,80550457,APAZA,CUARITE,JULIO CESAR,1,1977-11-30,6,2169,...,SÍ,525851214918,288787,1,Masculino,40-49,Subdirector Ninguno,NaN,NaN,NaN

In [93]:
# Modalidad EBR
variables = ["D1S1", "D1S2", "D1S3",
             "D1S4", "D2S5", "D2S6",
             "D2S7", "D3S8", "D3S9",
             "D3S10", "D3S11"
             ]

filtro = (

    (BD_R_DIF["ModalidadEducativa"] == "EBR") &
    (
        BD_R_DIF["ESTADODEEVALUACIÓN_actualizado"]
        .isin(["APROBADO", "DESAPROBADO", "PENDIENTE"])
    )
)

df_final = pd.concat([
    (
        BD_R_DIF[
            filtro &
            (BD_R_DIF[var].notna()) &
            (BD_R_DIF[var] != 0)
        ]
        .groupby(var)
        .size()
        .reset_index(name="n")
        .rename(columns={var: "categoria"})
        .assign(variable=var)
    )
    for var in variables
], ignore_index=True)

df_final.pivot_table(index="variable",
                     columns="categoria",
                     values="n",
                     fill_value=0)\
                         .reset_index()\
                         .to_excel("EBR_conteo_sd.xlsx",index=False)

In [94]:
# Modalidad EBA
variables = ["D1S1", "D1S2", "D1S3",
             "D1S4", "D2S5", "D2S6",
             "D2S7", "D3S8", "D3S9",
             "D3S10", "D3S11"
             ]

filtro = (

    (BD_R_DIF["ModalidadEducativa"] == "EBA") &
    (
        BD_R_DIF["ESTADODEEVALUACIÓN_actualizado"]
        .isin(["APROBADO", "DESAPROBADO", "PENDIENTE"])
    )
)

df_final_EBA = pd.concat([
    (
        BD_R_DIF[filtro]
        .groupby(var)
        .size()
        .reset_index(name="n")
        .rename(columns={var: "categoria"})
        .assign(variable=var)
    )

    for var in variables
], ignore_index=True)

df_final_EBA.pivot_table(index="variable",
                     columns="categoria",
                     values="n",
                     fill_value=0)\
                     .reset_index()\
                         .to_excel("EBA_conteo_sd.xlsx",index=False)

In [95]:
# Modalidad EBE
variables = ["D1S1", "D1S2", "D1S3",
             "D1S4", "D2S5", "D2S6",
             "D2S7", "D3S8", "D3S9",
             "D3S10", "D3S11"
             ]

filtro = (

    (BD_R_DIF["ModalidadEducativa"] == "EBE") &
    (
        BD_R_DIF["ESTADODEEVALUACIÓN_actualizado"]
        .isin(["APROBADO", "DESAPROBADO", "PENDIENTE"])
    )
)

df_final_EBE = pd.concat([
    (
        BD_R_DIF[filtro]
        .groupby(var)
        .size()
        .reset_index(name="n")
        .rename(columns={var: "categoria"})
        .assign(variable=var)
    )

    for var in variables
], ignore_index=True)

df_final_EBE.pivot_table(index="variable",
                     columns="categoria",
                     values="n",
                     fill_value=0)\
                     .reset_index()\
                         .to_excel("EBE_conteo_sd.xlsx",index=False)

In [59]:
BD_R_DIF[
    BD_R_DIF["ApePaternoEvaluado"]
    .str.startswith("POLAR", na=False)
]

,ID,tipo_doc,Documento,ApePaternoEvaluado,ApeMaternoEvaluado,NombreEvaluado,sex,fecha_nac,escala_final,IDLista,...,HABILITADO,CÓDIGODEPLAZA,CÓDIGOMODULAR,filter_$,DIF_sex,DIF_rango_edad,DIF_Perfil_evaluado,DIF_D1S2,DIF_D3S10,DIF_D3S11
2414,176571,1,16738998,POLAR,CORDOVA,ALBERTO SIGIFREDO,1,1975-04-27,6,3266,...,SÍ,023861213816,452599,0,Masculino,40-49,Director Sin función docente,NaN,NaN,NaN

Base nueva (?)

N = pd.read_

In [6]:
N = pd.read_excel(r"/Users/cristianmolina/Desktop/BD_EDDIR_Reg_Excep/Inputs/Consolidado_EDDirIE2024_22-12-2025_act.xlsx",
                  sheet_name="Consolidado_EDDirIE2024_22-12-2")

In [10]:
N

,ID,tipo_doc,ff,Documento,ApePaternoEvaluado,ApeMaternoEvaluado,NombreEvaluado,sex,fecha_nac,escala_final,...,Evaluado_actualizado,ESTADODEEVALUACIÓN_actualizado,OBSERVACIÓN,fecha_pub_hab,edad,edquin,grupedad,HABILITADO,CÓDIGODEPLAZA,CÓDIGOMODULAR
0,146653,1,1,1873,MONCADA,GONZALES,LUIS ALBERTO,1,1961-04-02,3,...,0,NO EVALUADO,NaN,2024-06-19,63,9,5,SÍ,1121113131I6,271205
1,193511,1,1,11467,RIOS,CORDOVA,TONY,1,1965-11-03,4,...,1,PENDIENTE,NaN,2024-06-19,58,8,4,SÍ,1132614311I4,1747971
2,213588,1,1,12733,SANCHEZ,ROJAS,CLAUDIA LUZ,2,1962-05-14,4,...,1,APROBADO,NaN,2024-06-19,62,9,5,SÍ,1140114111I3,913939
3,213494,1,1,15479,SANCHEZ,RIOS,CLOTILDE NATIVIDAD,2,1962-01-26,5,...,0,NO EVALUADO,NaN,2024-06-19,62,9,5,SÍ,1122313131I8,271296
4,143437,1,1,15657,MERA,OROSCO,PASTOR,1,1959-06-13,4,...,0,NO EVALUADO,NaN,2024-06-19,65,9,5,SÍ,1161115111I5,923383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5780,235543,1,1,80351513,URBANO,NIÑO,ROGELIO ELIAS,1,1976-12-19,6,...,1,APROBADO,NaN,2024-06-19,47,6,3,SÍ,520861219918,609503
5781,66888,1,1,80373161,CUNO,PUMA,MARCOS ABEL,1,1978-10-08,4,...,1,APROBADO,NaN,2024-06-19,45,6,3,SÍ,1134113010Q6,811745
5782,170936,1,1,80416941,PEÑALOZA,HUANCA,ALEXANDER RUSO,1,1976-03-07,5,...,1,PENDIENTE,NaN,2024-06-19,48,6,3,SÍ,1163114811E9,744441
5783,195576,1,1,80537531,RIVERA,PAREDES,JOHNNY,1,1979-04-14,5,...,1,APROBADO,NaN,2024-06-19,45,6,3,SÍ,1107313414N3,223578
5784,12639,1,1,80550457,APAZA,CUARITE,JULIO CESAR,1,1977-11-30,6,...,0,NO EVALUADO,NaN,2024-06-19,46,6,3,SÍ,525851214918,288787

In [12]:
variables = ["D1S1", "D1S2", "D1S3",
             "D1S4", "D2S5", "D2S6",
             "D2S7", "D3S8", "D3S9",
             "D3S10", "D3S11"
             ]

filtro = (

    (N["ModalidadEducativa"] == "EBR") &
    (
        N["ESTADODEEVALUACIÓN_actualizado"]
        .isin(["APROBADO", "DESAPROBADO", "PENDIENTE"])
    )
)

df_final = pd.concat([
    (
        N[
            filtro &
            (N[var].notna()) &
            (N[var] != 0)
        ]
        .groupby(var)
        .size()
        .reset_index(name="n")
        .rename(columns={var: "categoria"})
        .assign(variable=var)
    )
    for var in variables
], ignore_index=True)

df_final.pivot_table(index="variable",
                     columns="categoria",
                     values="n",
                     fill_value=0)\
                         .reset_index()\
                             .to_excel("EBR_conteo_sd_val.xlsx",index=False)

In [13]:
variables = ["D1S1", "D1S2", "D1S3",
             "D1S4", "D2S5", "D2S6",
             "D2S7", "D3S8", "D3S9",
             "D3S10", "D3S11"
             ]

filtro = (

    (N["ModalidadEducativa"] == "EBE") &
    (
        N["ESTADODEEVALUACIÓN_actualizado"]
        .isin(["APROBADO", "DESAPROBADO", "PENDIENTE"])
    )
)

df_final = pd.concat([
    (
        N[
            filtro &
            (N[var].notna()) &
            (N[var] != 0)
        ]
        .groupby(var)
        .size()
        .reset_index(name="n")
        .rename(columns={var: "categoria"})
        .assign(variable=var)
    )
    for var in variables
], ignore_index=True)

df_final.pivot_table(index="variable",
                     columns="categoria",
                     values="n",
                     fill_value=0)\
                         .reset_index()\
                             .to_excel("EBE_conteo_sd_val.xlsx",index=False)

In [14]:
variables = ["D1S1", "D1S2", "D1S3",
             "D1S4", "D2S5", "D2S6",
             "D2S7", "D3S8", "D3S9",
             "D3S10", "D3S11"
             ]

filtro = (

    (N["ModalidadEducativa"] == "EBA") &
    (
        N["ESTADODEEVALUACIÓN_actualizado"]
        .isin(["APROBADO", "DESAPROBADO", "PENDIENTE"])
    )
)

df_final = pd.concat([
    (
        N[
            filtro &
            (N[var].notna()) &
            (N[var] != 0)
        ]
        .groupby(var)
        .size()
        .reset_index(name="n")
        .rename(columns={var: "categoria"})
        .assign(variable=var)
    )
    for var in variables
], ignore_index=True)

df_final.pivot_table(index="variable",
                     columns="categoria",
                     values="n",
                     fill_value=0)\
                         .reset_index()\
                             .to_excel("EBA_conteo_sd_val.xlsx",index=False)

In [16]:
N[(N["ModalidadEducativa"]=="EBR") & (N["ESTADODEEVALUACIÓN_actualizado"].isin(
    ["APROBADO", "DESAPROBADO", "PENDIENTE"]
))]["D3S9"].value_counts(dropna=False)

D3S9
4.0    3184
1.0    1333
2.0     609
3.0     265
Name: count, dtype: int64